from os import listdir

# infographics_file_names = listdir(r'..\static\afiches')

infographics_dict = {
    'acanthogonatus sp': 'genero_acanthogonatus.jpg',
    'allende sp': 'familia_tetragnathidae.jpg',
    'tetragnatha sp': 'familia_tetragnathidae.jpg',
    'anyphaenidae': 'familia_anyphaenidae.jpg',
    'argiope argentata': 'genero_argiope.jpg',
    'argiope trifasciata': 'genero_argiope.jpg',
    'ariadna sp': 'genero_ariadna.jpg',
    'austrochilidae': 'familia_austrochilidae.jpg',
    'doliomalus cimicoides': 'especie_doliomalus_cimicoides.jpg',
    'dysdera crocata': 'especie_dysdera_crocata.jpg',
    'euathlus manicata': 'especie_euathlus_manicata.jpg',
    'euathlus truculentus': 'especie_euathlus_truculentus.jpg',
    'gnaphosidae': 'familia_gnaphosidae.jpg',
    'gnolus sp': 'genero_gnolus.jpg',
    'grammostola rosea': 'especie_grammostola_rosea.jpg',
    'homoeomma': 'genero_homoeomma.jpg',
    'latrodectus sp': 'genero_latrodectus.jpg',
    'loxosceles laeta': 'genero_loxosceles.jpg',
    'lycosidae': 'familia_lycosidae.jpg',
    'lyniphiidae': 'familia_linyphiidae.jpg',
    'macerio': 'genero_macerio.jpg',
    'mastophora sp': 'genero_mastophora.jpg',
    'menemerus semilimbatus': 'familia_salticidae.jpg',
    'saphrys rusticana': 'familia_salticidae.jpg',
    'metepeira sp': 'genero_metepeira.jpg',
    'misumenops sp': 'familia_thomisidae.jpg',
    'coenypha sp': 'familia_thomisidae.jpg',
    'molinaranea clymene': 'especie_molinaranea_clymene.jpg',
    'molinaranea magellanica': 'especie_molinaranea_magellanica.jpg',
    'ocrepeira sp': 'especie_ocrepeira_venustula.jpg',
    'oecobius sp': 'genero_oecobius.jpg',
    'pachylus': 'orden_opilones.jpg',
    'sadocus_sp': 'orden_opilones.jpg',
    'petrichus sp': 'genero_petrichus.jpg',
    'pholcidae': 'familia_pholcidae.jpg',
    'phrixotrichus sp': 'familia_theraphosidae.jpg',
    'plesionela bonneti': 'especie_plesiolena_bonneti.jpg',
    'polybetes sp': 'genero_polybetes.jpg',
    'scytodes globula': 'genero_scytodes.jpg',
    'sicarius': 'genero_sicarius.jpg',
    'steatoda grossa': 'genero_steatoda.jpg',
    'steatoda nobilis': 'genero_steatoda.jpg',
    'steatoda triangulosa': 'genero_steatoda.jpg',
    'sybota sp': 'familia_uloboridae.jpg',
    'zygiella x-notata': 'especie_zygiella_x-notata.jpg',
    'no_info': 'no_afiche.png'
}
